/* extracted from https://www.bottlecaps.de/rr/ui on Fri Mar 29, 2019, 00:15 (UTC+01)
 */
 
ExpressionLanguage ::= '[' Expression ']'
Expression ::= AndExpression | OrExpression | AtomicExpression
AndExpression ::= '{ "and": [' Expression (',' Expression)* ']}'
OrExpression ::= '{ "or": [' Expression (',' Expression)* ']}'
AtomicExpression ::= '{' (ContainerEvent | ActivityEvent) '}'
ContainerEvent ::= '"type":"container", "concept":' Object (',"id_":' Name)? ', "state":' ContainerState
ContainerState ::= '"full"' | '"empty"'
ActivityEvent ::= '"type":"activity", '('"ID":' ID | '"name":' Name) ', "state":' ActivityState
ActivityState ::= '"done"'
ID ::= String
Name ::= String